import { attachTabs }   from '../core/tabs.js';
import { risksData }    from '../data/risks/risks-data.js';
import { riskMapping }  from '../data/risks/risks-mapping.js';

// The original file declared initRisks() twice; the second declaration (l.1159)
// was the active one at runtime. This module preserves that final behaviour.
// showRisksInCell is exposed on window because the matrix cells use inline
// onclick handlers generated by renderRiskMatrix (business-logic preservation).

const levelColors = { critical: '#e53935', elevated: '#f9a825', moderate: '#43a047' };
const levelLabels = { critical: 'Critique', elevated: 'Élevé', moderate: 'Modéré' };

// Verbatim (index.html l.1202-1268).
function renderRiskMatrix(phase) {
  const risks = risksData[phase];
  const mapping = riskMapping[phase];
  if (!risks || !mapping) return '';

  const getColor = (prob, impact) => {
    const score = prob * impact;
    if (score >= 20) return '#e53935';
    if (score >= 15) return '#ef5350';
    if (score >= 12) return '#ff7043';
    if (score >= 9) return '#ffa726';
    if (score >= 6) return '#ffca28';
    return '#66bb6a';
  };

  const cellRisks = {};
  mapping.forEach(m => {
    const key = m.prob + '-' + m.impact;
    if (!cellRisks[key]) cellRisks[key] = [];
    cellRisks[key].push({...risks[m.idx], idx: m.idx});
  });

  let h = '<div style="margin:40px 0"><h2 style="text-align:center;margin-bottom:30px;font-size:20px">Matrice des Risques - Phase ' + phase.replace('p','') + '</h2>';
  h += '<div style="max-width:1000px;margin:0 auto"><table style="width:100%;border-collapse:collapse;background:var(--card);border:2px solid var(--bdr)">';
  h += '<thead><tr><th style="width:140px;padding:10px;border:1px solid var(--bdr);background:rgba(255,255,255,0.03);font-size:11px"></th>';

  const impactLabels = ['1 Insignifiant', '2 Mineure', '3 Significative', '4 Majeure', '5 Sévère'];
  impactLabels.forEach(label => {
    h += '<th style="padding:10px;border:1px solid var(--bdr);background:rgba(255,255,255,0.03);font-size:11px;text-align:center">' + label + '</th>';
  });
  h += '</tr></thead><tbody>';

  const probLabels = ['1 Rare', '2 Improbable', '3 Modéré', '4 Probable', '5 Presque certain'];
  for (let prob = 5; prob >= 1; prob--) {
    h += '<tr><td style="padding:10px;border:1px solid var(--bdr);background:rgba(255,255,255,0.03);font-size:11px">' + probLabels[prob-1] + '</td>';

    for (let impact = 1; impact <= 5; impact++) {
      const key = prob + '-' + impact;
      const cellRiskList = cellRisks[key] || [];
      const color = getColor(prob, impact);
      const score = prob * impact;
      const hasRisks = cellRiskList.length > 0;

      h += '<td style="padding:8px;border:1px solid var(--bdr);background:' + color + ';min-height:60px;cursor:' + (hasRisks ? 'pointer' : 'default') + ';transition:opacity 0.2s" ';
      h += 'onmouseover="if(this.style.cursor===\'pointer\')this.style.opacity=\'0.8\'" ';
      h += 'onmouseout="this.style.opacity=\'1\'" ';
      if (hasRisks) {
        h += 'onclick="showRisksInCell(\'' + phase + '\',\'' + key + '\')"';
      }
      h += '>';
      h += '<div style="font-size:10px;font-weight:700;color:rgba(0,0,0,0.6);margin-bottom:4px">Score ' + score + '</div>';

      if (hasRisks) {
        h += '<div style="display:flex;flex-wrap:wrap;gap:3px">';
        cellRiskList.forEach(r => {
          h += '<div style="font-size:9px;background:rgba(0,0,0,0.2);color:#fff;padding:2px 6px;border-radius:10px;font-weight:600">R' + (r.idx+1) + '</div>';
        });
        h += '</div>';
      }
      h += '</td>';
    }
    h += '</tr>';
  }

  h += '</tbody></table></div></div>';
  return h;
}

// Verbatim (index.html l.1050-1089).
function renderRisks(phase) {
  const container = document.getElementById('r-' + phase);
  if (!container || container.innerHTML.trim() !== '') return;
  const risks = risksData[phase];
  if (!risks) return;

  let h = renderRiskMatrix(phase) + '<h2 style="margin:40px 0 20px;text-align:center;font-size:18px">Liste Détaillée</h2><div style="display:flex;flex-direction:column;gap:18px">';
  risks.forEach((r) => {
    const col = levelColors[r.level];
    const label = levelLabels[r.level];
    h += `
    <div style="background:var(--card);border:1px solid ${col}44;border-left:4px solid ${col};border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.25)">
      <div style="padding:16px 20px 10px">
        <div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap">
          <span style="font-size:18px;font-weight:700;color:#fff">${r.title}</span>
          <span style="background:${col};color:#fff;font-size:10px;font-weight:700;padding:3px 10px;border-radius:20px;text-transform:uppercase;letter-spacing:.06em">${label}</span>
        </div>
        <p style="color:var(--t2);font-size:13px;margin:10px 0 0;line-height:1.55">${r.desc}</p>
        <div style="margin-top:10px;display:flex;align-items:center;gap:6px">
          <span style="font-size:11px;color:var(--t2);opacity:.7">Acteurs :</span>
          <span style="font-size:11px;font-weight:600;color:#d4f1f4;background:rgba(0,245,255,0.13);border:1px solid rgba(0,245,255,0.28);padding:3px 8px;border-radius:6px;line-height:1.5">${r.actors}</span>
        </div>
      </div>
      <div style="padding:0 20px 16px">
        <div style="font-size:11px;font-weight:700;color:${col};text-transform:uppercase;letter-spacing:.08em;margin-bottom:8px">KPIs de mitigation</div>
        <div style="display:flex;flex-direction:column;gap:6px">
          ${r.kpis.map(k => `<div style="display:flex;align-items:flex-start;gap:8px;background:rgba(255,255,255,.04);padding:8px 12px;border-radius:7px">
            <span style="color:${col};font-size:14px;flex-shrink:0;margin-top:1px">▸</span>
            <span style="font-size:12px;color:var(--t2);line-height:1.45">${k}</span>
          </div>`).join('')}
        </div>
      </div>
    </div>`;
  });
  h += '</div>';
  container.innerHTML = h;
}

// Verbatim (index.html l.1270-1315). Exposed globally for inline handlers in the matrix.
export function showRisksInCell(phase, cellKey) {
  const risks = risksData[phase];
  const mapping = riskMapping[phase];
  if (!risks || !mapping) return;

  const [prob, impact] = cellKey.split('-').map(Number);
  const cellRiskList = mapping.filter(m => m.prob === prob && m.impact === impact).map(m => ({...risks[m.idx], idx: m.idx}));

  if (cellRiskList.length === 0) return;

  const overlay = document.getElementById('modalOverlay');
  const inner = document.getElementById('modalInner');

  let h = '<div style="max-width:800px;max-height:85vh;overflow-y:auto;padding:20px">';
  h += '<h2 style="color:#fff;margin-bottom:20px">Risques : Probabilité ' + prob + ' × Impact ' + impact + '</h2>';
  h += '<div style="display:flex;flex-direction:column;gap:20px">';

  cellRiskList.forEach(r => {
    const col = levelColors[r.level];
    const label = levelLabels[r.level];
    h += '<div style="background:var(--card);border:1px solid ' + col + '44;border-left:4px solid ' + col + ';border-radius:12px;padding:18px">';
    h += '<div style="display:flex;align-items:center;gap:10px;margin-bottom:10px">';
    h += '<span style="font-size:16px;font-weight:700;color:#fff">' + r.title + '</span>';
    h += '<span style="background:' + col + ';color:#fff;font-size:9px;font-weight:700;padding:3px 8px;border-radius:12px">' + label + '</span>';
    h += '</div>';
    h += '<p style="color:var(--t2);font-size:13px;line-height:1.5;margin-bottom:12px">' + r.desc + '</p>';
    h += '<div style="margin-bottom:8px">';
    h += '<span style="font-size:10px;color:var(--t2);opacity:0.7">Acteurs :</span>';
    h += '<span style="font-size:11px;font-weight:600;color:#d4f1f4;background:rgba(0,245,255,0.13);border:1px solid rgba(0,245,255,0.28);padding:2px 6px;border-radius:4px;margin-left:6px">' + r.actors + '</span>';
    h += '</div>';
    h += '<div style="font-size:10px;font-weight:700;color:' + col + ';text-transform:uppercase;margin-top:12px;margin-bottom:6px">KPIs</div>';
    r.kpis.forEach(k => {
      h += '<div style="font-size:11px;color:var(--t2);margin-bottom:4px">▸ ' + k + '</div>';
    });
    h += '</div>';
  });

  h += '</div></div>';

  inner.innerHTML = h;
  overlay.classList.add('active');
  document.body.style.overflow = 'hidden';
}

// Verbatim (index.html l.1159-1171 — the second, winning definition).
export function initRisks() {
  attachTabs('risks-tabs');
  renderRisks('p1');

  document.querySelectorAll('#risks-tabs .tab').forEach(tab => {
    tab.addEventListener('click', function () {
      const tabId = this.getAttribute('data-tab');
      const phase = tabId.replace('r-', '');
      renderRisks(phase);
    });
  });
}
